# Generated by Django 2.1.5 on 2019-03-03 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasMileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_date', models.DateField()),
                ('trip', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, max_length=150)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.Motorcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
