# Generated by Django 2.1.5 on 2019-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasMileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_date', models.DateField()),
                ('trip', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, max_length=150)),
                ('bike', models.ManyToManyField(to='motorcycles.Motorcycle')),
            ],
        ),
    ]
