# Generated by Django 2.1.5 on 2019-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('ya', 'YAMAHA'), ('ho', 'HONDA'), ('ka', 'KAWASAKI'), ('su', 'SUZUKI')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('sc', 'Scouter'), ('bs', 'Big_Scouter'), ('ss', 'Super_Sport'), ('of', 'Offroad')], max_length=2)),
                ('engine_displacement', models.IntegerField()),
                ('model_number', models.CharField(max_length=20)),
                ('model_year', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
