# Generated by Django 2.1.5 on 2019-03-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='model_year',
            field=models.CharField(max_length=20),
        ),
    ]
