# Generated by Django 2.1.5 on 2019-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_auto_20190303_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='model_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='model_year',
            field=models.DateField(),
        ),
    ]
